/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class segfault_hydrolog_nativelib_Uptime */

#ifndef _Included_segfault_hydrolog_nativelib_Uptime
#define _Included_segfault_hydrolog_nativelib_Uptime
/*
 * Class:     segfault_hydrolog_nativelib_Uptime
 * Method:    uptime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_segfault_hydrolog_nativelib_Uptime_uptime
  (JNIEnv *, jclass);

#endif
